# Generated by Django 5.0.4 on 2024-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(max_length=100),
        ),
    ]
