# Generated by Django 5.0.4 on 2024-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('boarder', 'Boarder'), ('day_scholar', 'Day Scholar')], default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Khaja Bagh', 'Khaja Bagh'), ('Akber Bagh', 'Akber Bagh'), ('Ghatkesar', 'Ghatkesar'), ('Bandlaguda', 'Bandlaguda')], max_length=100),
        ),
    ]
