# Generated by Django 5.0.4 on 2024-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_student_student_type_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_darja',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
