# Generated by Django 5.0.4 on 2024-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_student_class_darja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
