# Generated by Django 5.0.6 on 2024-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_alter_student_course_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(choices=[('Academic Fee', 'Academic Fee'), ('Tuition Fee', 'Tuition Fee'), ('Mess Fee', 'Mess Fee'), ('Hostel Fee', 'Hostel Fee'), ('Library Fee', 'Library Fee'), ('Stationary Fee', 'Stationary Fee')], default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
