# Generated by Django 5.0.6 on 2024-07-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alter_student_class_darja_alter_student_course'),
        ('fees', '0014_payment_fee_type'),
    ]

    operations = [
    ]
