# Generated by Django 5.0.6 on 2024-07-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_payment_payment_method_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fees.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fees.organization'),
            preserve_default=False,
        ),
    ]
