# Generated by Django 5.0.6 on 2024-07-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0022_organization_payment_year_payment_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.organization'),
        ),
    ]
