# Generated by Django 5.0.6 on 2024-07-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0023_remove_student_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
