# Generated by Django 5.0.6 on 2024-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_alter_payment_organization_alter_payment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('book_no', 'receipt_no')},
        ),
    ]
