# Generated by Django 5.0.6 on 2024-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0026_alter_payment_book_no_alter_payment_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(default='Fee', max_length=15),
        ),
    ]
