# Generated by Django 5.0.6 on 2024-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0027_alter_payment_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('branch1', 'Branch 1'), ('branch2', 'Branch 2'), ('branch3', 'Branch 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('course1', 'Course 1'), ('course2', 'Course 2'), ('course3', 'Course 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3')], max_length=10, null=True),
        ),
    ]
