# Generated by Django 5.0.6 on 2024-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0028_alter_student_branch_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('fee', 'Fee'), ('donation', 'Donation'), ('other', 'Other')], default='fee', max_length=15),
        ),
    ]
