# Generated by Django 5.0.6 on 2024-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0029_alter_payment_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('boarder', 'Boarder')], default='Boarder', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
