# Generated by Django 5.0.6 on 2024-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0030_student_student_type_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Akber Bagh', 'Akber Bagh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.COM - I', 'B.COM - I')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Day Scholar', 'Day Scholar'), ('Boarder', 'Boarder')], default='Boarder', max_length=20),
        ),
    ]
